name: Unit Tests
on: 
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "The pull request was merged"
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test